### ISSUE TITLE
[WIP] HighNodeUsage policy

### ISSUE THREAD

**Issue by ringtail** [kubernetes-sigs/descheduler#538] opened 2021-03-31 09:22 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes the node is under high pressure because of resource oversold and we would like to evict some low priority pods to other nodes if necessary.

**Describe the solution you'd like**
1. Get Metrics from metrics API from kubernetes [resource metrics/custom metrics/external metrics].
2. Check the threshold and pick the candidate pod.
3. Complete rescheduling

**What version of descheduler are you using?**

descheduler version:
latest version 

**Additional context**
We have implemented a beta version base on resource metrics api with metrics server. And we would like to  make it more generic with three types of metric interfaces.

**Comment by damemi** [comment] 2021-03-31 14:16
@ringtail thanks for opening this, it seems like a duplicate of https://github.com/kubernetes-sigs/descheduler/issues/225 which discusses adding real load aware usage to the LowNodeUtilization strategy.

If you already have a beta version implemented, would you be interested in opening a PR so we can discuss implementing it here?

**Comment by ringtail** [comment] 2021-04-01 06:40
@damemi Cool! Is the pre issue in developing? I would like to merge the code with it.

**Comment by damemi** [comment] 2021-04-01 13:30
It doesn't look like it's being actively worked on right now, but we can close this one and move the discussion over to there.

Feel free to open a PR if you have changes available!
/close

**Closed by damemi** 2021-04-01 13:30 UTC
Labels: kind/feature

**Comment by ringtail** [comment] 2021-04-02 02:27
> It doesn't look like it's being actively worked on right now, but we can close this one and move the discussion over to there.
> 
> Feel free to open a PR if you have changes available!
> /close

Sure, I'll submit a new proposal based on the idea you discussed before.
