### ISSUE TITLE
the cpu& mem policy has no effect

### ISSUE THREAD

**Issue by auqf** [kubernetes-sigs/descheduler#588] opened 2021-06-15 16:37 UTC
![image](https://user-images.githubusercontent.com/8895540/122090493-62721200-ce3a-11eb-92f2-0455b9e02b58.png)

**What version of descheduler are you using?**

descheduler version:
v0.21.0

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
cronjob

**Please provide a copy of your descheduler policy config file**
![image](https://user-images.githubusercontent.com/8895540/122090742-b11fac00-ce3a-11eb-8242-cc7bdddbac57.png)

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

**What did you expect to see?**
why the mapuseage is so low?

**What did you see instead?**
![image](https://user-images.githubusercontent.com/8895540/122091113-0b207180-ce3b-11eb-8631-3be84fe19de9.png)

**Comment by damemi** [comment] 2021-06-15 17:31
Hi @auqf 
The descheduler doesn't currently calculate node usage based on consumption metrics (which `kubectl top` uses to get those percentages). Rather, it relies solely on the requested resources from pods.

Could you share the `kubect describe <node>` output for some of these nodes? That will show the requested resources and may explain why the usage percentages you see in the Descheduler logs are different

**Comment by auqf** [comment] 2021-06-16 01:48
the info as follows:
![image](https://user-images.githubusercontent.com/8895540/122145444-d8509a80-ce87-11eb-8c84-92d3d1cc75bf.png)
![image](https://user-images.githubusercontent.com/8895540/122145547-08983900-ce88-11eb-9b16-7b827f75a7bd.png)

**Comment by damemi** [comment] 2021-06-16 13:01
@auqf ah, yes that is the explanation then. Your pods are only requesting 1-2% of the node's available resources even though they are actually consuming much more than that. We have an open issue to use the metrics available to provide "real usage" load balancing, though it hasn't received much activity in a while: https://github.com/kubernetes-sigs/descheduler/issues/225. I believe at this point we can close this issue as a duplicate of that one, do you agree?

As a side note, we do recommend attempting to put accurate resource requests on your workloads, because these numbers also affect scheduling. For example, even if the Descheduler were to evict your pods right now based on their actual usage, they may not be scheduled in the intended "balanced" way because the scheduler only sees their requests and will schedule based on that. So, they could end up on the same nodes again.

**Comment by auqf** [comment] 2021-06-17 01:31
ok

**Closed** 2021-06-17 12:28 UTC
Labels: kind/bug
