### ISSUE TITLE
Add support for pod deletion (vs. eviction)

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes-sigs/descheduler#1253] opened 2023-10-03 16:38 UTC
There are times when "evict" is not sufficient to remove pods.

Consider a use-case when the pod is stuck in the "Terminating" state, which could happen for various reasons, but mainly due to the "kubelet" related issues (not running, network, etc).

Currently, we typically run `kubectl delete --force --grace-period=0` to overcome this issue. 

Granted, such a workaround is not always applicable to all workloads (for example, stateful, etc.).
It is still could be very useful to craft a policy that would address the use case of pods stuck in a "Terminating" state.

**Comment by a7i** [comment] 2023-10-07 13:44
Duplicate of #1170

**Closed** 2024-03-29 22:56 UTC
Labels: kind/feature, lifecycle/rotten
