### ISSUE TITLE
Support node status is not ready auto delete pod status is Terminating

### ISSUE THREAD

**Issue by wxuedong** [kubernetes-sigs/descheduler#797] opened 2022-05-16 08:25 UTC
When the node status is unavailable or the network is abnormal, the deleted pod status will always be in Terminating, 

 if the app is being  canary deploy or rolling update at this time . deploy paused because pod were not deleted properly.

At this time, the administrator needs to forcefully delete the pod, and the progress returns to normal.

So I think adding a policy to automatically delete pods that have been in Terminating for a long time.

**Comment by damemi** [comment] 2022-05-16 13:06
Hi @wxuedong,
I think this is essentially a duplicate of https://github.com/kubernetes-sigs/descheduler/issues/766. tl;dr from there is that the descheduler doesn't force-delete pods, it uses the eviction API to safely evict them from the cluster. If they are stuck in terminating, there may be other options to tweak it outside of descheduling such as adjusting the grace period.

I'm going to close this issue as a duplicate, but feel free to continue discussion in the one I just linked if there is more to add. Thanks!
/close

**Closed** 2022-05-16 13:06 UTC
Labels: kind/feature
