### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by william89731** [kubernetes-sigs/descheduler#1248] opened 2023-09-21 11:11 UTC
```log descheduler:```

![image](https://github.com/kubernetes-sigs/descheduler/assets/68069659/1ce0e7fb-aacb-4409-b473-7066daf304c3)

```metrics server:```

![image](https://github.com/kubernetes-sigs/descheduler/assets/68069659/d1b56b47-2f54-471a-ad88-d9e132287f4e)

```kubectl and microk8s version:```

![image](https://github.com/kubernetes-sigs/descheduler/assets/68069659/e69d811c-3ffe-4e55-97cc-77240a4c9c98)

```descheduler version:```

[0.28](https://github.com/kubernetes-sigs/descheduler/tree/master/kubernetes)

**Comment by a7i** [comment] 2023-09-22 00:43
Hi @william89731 
Descheduler is not using metrics-server but only looks at container requests.

duplicate of: https://github.com/kubernetes-sigs/descheduler/issues/1240

/kind support

**Comment by a7i** [comment] 2023-10-27 02:29
/close

feel free to reopen

**Closed by a7i** 2023-10-27 02:29 UTC
Labels: kind/support
