### ISSUE TITLE
mismatch in nodes resource calculations 

### ISSUE THREAD

**Issue by anil-venkata** [kubernetes-sigs/descheduler#666] opened 2021-12-03 07:30 UTC
**What version of descheduler are you using?**

descheduler version: Descheduler v0.22.1

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**
```
            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--descheduling-interval"
            - "5m"
            - "--v"
            - "3"
```

**Please provide a copy of your descheduler policy config file**

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 20
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 50
               "memory": 50
               "pods": 50
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

There is miss match in the resource calculations.
i see mismatch in the resource calculations. 

```
I1203 06:50:40.802820       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-1-110.eu-central-1.compute.internal" usage=map[cpu:1022m memory:936Mi pods:9] usagePercentage=map[cpu:52.95336787564767 memory:12.677250088089366 pods:45]
I1203 06:50:40.802878       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-1-148.eu-central-1.compute.internal" usage=map[cpu:1822m memory:4664Mi pods:14] usagePercentage=map[cpu:94.4041450777202 memory:63.1695453107359 pods:70]
I1203 06:50:40.802914       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-1-45.eu-central-1.compute.internal" usage=map[cpu:1922m memory:4350Mi pods:16] usagePercentage=map[cpu:99.58549222797927 memory:58.91670714015891 pods:80]
I1203 06:50:40.802946       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-10-110.eu-central-1.compute.internal" usage=map[cpu:1522m memory:3600Mi pods:13] usagePercentage=map[cpu:78.860103626943 memory:48.7586541849591 pods:65]
I1203 06:50:40.802988       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-10-145.eu-central-1.compute.internal" usage=map[cpu:1722m memory:4800Mi pods:14] usagePercentage=map[cpu:89.22279792746114 memory:65.0115389132788 pods:70]
I1203 06:50:40.803030       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-10-5.eu-central-1.compute.internal" usage=map[cpu:1822m memory:5036Mi pods:16] usagePercentage=map[cpu:94.4041450777202 memory:68.207939576515 pods:80]
I1203 06:50:40.803073       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-10-58.eu-central-1.compute.internal" usage=map[cpu:1632m memory:1820Mi pods:15] usagePercentage=map[cpu:84.55958549222798 memory:24.65020850461821 pods:75]
I1203 06:50:40.803108       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-10-97.eu-central-1.compute.internal" usage=map[cpu:1922m memory:5228Mi pods:14] usagePercentage=map[cpu:99.58549222797927 memory:70.80840113304616 pods:70]
I1203 06:50:40.803144       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-11-183.eu-central-1.compute.internal" usage=map[cpu:1722m memory:3864Mi pods:14] usagePercentage=map[cpu:89.22279792746114 memory:52.33428882518943 pods:70]
I1203 06:50:40.803188       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-12-151.eu-central-1.compute.internal" usage=map[cpu:1022m memory:1608Mi pods:10] usagePercentage=map[cpu:52.95336787564767 memory:21.7788655359484 pods:50]
I1203 06:50:40.803230       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-12-250.eu-central-1.compute.internal" usage=map[cpu:1822m memory:3364Mi pods:14] usagePercentage=map[cpu:94.4041450777202 memory:45.56225352172289 pods:70]
I1203 06:50:40.803268       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-12-54.eu-central-1.compute.internal" usage=map[cpu:1522m memory:3400Mi pods:12] usagePercentage=map[cpu:78.860103626943 memory:46.04984006357248 pods:60]
I1203 06:50:40.803311       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-13-105.eu-central-1.compute.internal" usage=map[cpu:1722m memory:2556Mi pods:17] usagePercentage=map[cpu:89.22279792746114 memory:34.61864447132096 pods:85]
I1203 06:50:40.803348       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-13-218.eu-central-1.compute.internal" usage=map[cpu:1822m memory:3728Mi pods:17] usagePercentage=map[cpu:94.4041450777202 memory:50.49229522264653 pods:85]
I1203 06:50:40.803395       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-13-4.eu-central-1.compute.internal" usage=map[cpu:922m memory:1208Mi pods:9] usagePercentage=map[cpu:47.7720207253886 memory:16.361237293175165 pods:45]
I1203 06:50:40.803474       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-2-91.eu-central-1.compute.internal" usage=map[cpu:1122m memory:2744Mi pods:12] usagePercentage=map[cpu:58.134715025906736 memory:37.16492974542438 pods:60]
I1203 06:50:40.803540       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-3-109.eu-central-1.compute.internal" usage=map[cpu:1422m memory:5072Mi pods:15] usagePercentage=map[cpu:73.67875647668394 memory:68.6955261183646 pods:75]
I1203 06:50:40.803602       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-7-133.eu-central-1.compute.internal" usage=map[cpu:1822m memory:3050Mi pods:18] usagePercentage=map[cpu:94.4041450777202 memory:41.3094153511459 pods:90]
I1203 06:50:40.803683       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-7-189.eu-central-1.compute.internal" usage=map[cpu:1822m memory:4064Mi pods:14] usagePercentage=map[cpu:94.4041450777202 memory:55.04310294657605 pods:70]
I1203 06:50:40.803733       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-7-215.eu-central-1.compute.internal" usage=map[cpu:1922m memory:4464Mi pods:15] usagePercentage=map[cpu:99.58549222797927 memory:60.46073118934928 pods:75]
I1203 06:50:40.803771       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-7-7.eu-central-1.compute.internal" usage=map[cpu:922m memory:1408Mi pods:10] usagePercentage=map[cpu:47.7720207253886 memory:19.07005141456178 pods:50]
I1203 06:50:40.803805       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-7-9.eu-central-1.compute.internal" usage=map[cpu:1822m memory:3006Mi pods:18] usagePercentage=map[cpu:94.4041450777202 memory:40.71347624444085 pods:90]
I1203 06:50:40.803856       1 nodeutilization.go:167] "Node is overutilized" node="ip-172-32-8-107.eu-central-1.compute.internal" usage=map[cpu:1922m memory:5128Mi pods:14] usagePercentage=map[cpu:99.58549222797927 memory:69.45399407235284 pods:70]
I1203 06:50:40.803901       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-8-203.eu-central-1.compute.internal" usage=map[cpu:1322m memory:4128Mi pods:12] usagePercentage=map[cpu:68.49740932642487 memory:55.909923465419766 pods:60]
I1203 06:50:40.803934       1 nodeutilization.go:170] "Node is appropriately utilized" node="ip-172-32-8-84.eu-central-1.compute.internal" usage=map[cpu:652m memory:1110Mi pods:10] usagePercentage=map[cpu:33.78238341968912 memory:15.033918373695721 pods:50]

```

But in my `kubectl top nodes` i see different results

```
NAME                                             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-172-32-1-110.eu-central-1.compute.internal    110m         5%     854Mi           11%
ip-172-32-1-148.eu-central-1.compute.internal    133m         6%     2116Mi          28%
ip-172-32-1-45.eu-central-1.compute.internal     157m         8%     2587Mi          35%
ip-172-32-10-110.eu-central-1.compute.internal   133m         6%     1200Mi          16%
ip-172-32-10-145.eu-central-1.compute.internal   142m         7%     2042Mi          27%
ip-172-32-10-5.eu-central-1.compute.internal     151m         7%     2445Mi          33%
ip-172-32-10-58.eu-central-1.compute.internal    127m         6%     2020Mi          27%
ip-172-32-10-97.eu-central-1.compute.internal    132m         6%     2600Mi          35%
ip-172-32-11-183.eu-central-1.compute.internal   224m         11%    2325Mi          31%
ip-172-32-12-151.eu-central-1.compute.internal   102m         5%     1150Mi          15%
ip-172-32-12-250.eu-central-1.compute.internal   155m         8%     1948Mi          26%
ip-172-32-12-54.eu-central-1.compute.internal    159m         8%     1176Mi          15%
ip-172-32-13-105.eu-central-1.compute.internal   176m         9%     2716Mi          36%
ip-172-32-13-218.eu-central-1.compute.internal   184m         9%     1559Mi          21%
ip-172-32-13-4.eu-central-1.compute.internal     94m          4%     919Mi           12%
ip-172-32-2-91.eu-central-1.compute.internal     125m         6%     1000Mi          13%
ip-172-32-3-109.eu-central-1.compute.internal    150m         7%     2992Mi          40%
ip-172-32-7-133.eu-central-1.compute.internal    186m         9%     1999Mi          27%
ip-172-32-7-189.eu-central-1.compute.internal    176m         9%     2506Mi          33%
ip-172-32-7-215.eu-central-1.compute.internal    146m         7%     2670Mi          36%
ip-172-32-7-7.eu-central-1.compute.internal      104m         5%     1376Mi          18%
ip-172-32-7-9.eu-central-1.compute.internal      661m         34%    2973Mi          40%
ip-172-32-8-107.eu-central-1.compute.internal    186m         9%     1826Mi          24%
ip-172-32-8-203.eu-central-1.compute.internal    544m         28%    5634Mi          76%
ip-172-32-8-84.eu-central-1.compute.internal     140m         7%     827Mi           11%
```

**What did you expect to see?**
Descheduler must pick the nodes that are less consuming

**What did you see instead?**
It says overutilized

**Comment by damemi** [comment] 2021-12-03 13:56
@anil-venkata the descheduler and kubectl will report different values for memory. This is because the descheduler calculates usage based only on the requests/limits of pods, not what they are actually using (this is the same behavior the scheduler uses, so we remain consistent to ensure better performance during evictions). Kubectl reports actual memory usage from the metrics server.

A proposal to do this based on actual usage metrics is open here: https://github.com/kubernetes-sigs/descheduler/issues/225

For more details, this has been discussed in several other issues, eg https://github.com/kubernetes-sigs/descheduler/issues/628 https://github.com/kubernetes-sigs/descheduler/issues/270 https://github.com/kubernetes-sigs/descheduler/issues/118
/close
(as duplicate of the above)

**Closed** 2021-12-03 13:56 UTC
Labels: kind/bug

**Comment by 19bcs2405** [comment] 2023-08-28 13:00
@anil-venkata is your issues fixed ?
Because i am getting same error

**Comment by anil-venkata** [comment] 2023-08-29 06:02
@19bcs2405 , looks like #225 is still in open state , which indicates it is not implemented yet.

**Comment by 19bcs2405** [comment] 2023-08-29 07:04
@anil-venkata Is there any other way to solve the problem.
