### ISSUE TITLE
Is there a plan to support the strategy of rescheduling according to the real load of the node?

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes-sigs/descheduler#1039] opened 2023-01-10 08:31 UTC
Is there a plan to support the strategy of rescheduling according to the real load of the node?

**Comment by damemi** [comment] 2023-01-10 14:32
Hi, this has been requested and we have a pinned issue with discussion around it: https://github.com/kubernetes-sigs/descheduler/issues/225

In short there's nothing blocking this, but it will require extra cluster add-ons (like metrics-server) and likely the use of a custom scheduler plugin to be really effective. Because of that it hasn't been prioritized, but we're still open to adding it someday.

Closing this as duplicate of that issue, please feel free to discuss there.
/close

**Closed by damemi** 2023-01-10 14:32 UTC
Labels: kind/feature
