### ISSUE TITLE
 Exclude namespace is invalid

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-sigs/descheduler#511] opened 2021-03-01 03:38 UTC
Hi：
          kubernetes version:  v1.16.9
         descheduler version:  v0.20.0
         Exclude namespace is invalid
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "PodLifeTime":
         enabled: true
         params:
            podLifeTime:
              maxPodLifeTimeSeconds: 86400
            namespaces:
              include:
              - "dev"
              exclude:
              - "kube-system"
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 50
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 70
               "memory": 30
               "pods": 20
```
![248A9953-357A-41d1-B559-34C04A04465B](https://user-images.githubusercontent.com/5716348/109467276-eaa7f380-7aa5-11eb-9686-fc2feedbce42.png)

**Comment by damemi** [comment] 2021-03-01 14:22
Hi @1032231418 ,
from the logs you posted, I see that the pod in kube-system was evicted due to the `LowNodeUtilization` strategy, which does not have the ability to filter specific namespaces.

For critical pods which should never be evicted, you should consider using a [system-critical priority class](https://github.com/kubernetes-sigs/descheduler#pod-evictions) or your own priority class and set [priority thresholds](https://github.com/kubernetes-sigs/descheduler#priority-filtering) on each strategy. Both of these options are supported by all strategies

/remove-kind bug
/kind support

**Comment by 1032231418** [comment] 2021-03-02 05:04
@damemi  
My purpose is to perform migration in one namespace, and isolate the other namespace, because it acts on the entire cluster and causes business exceptions.

**Comment by 1032231418** [comment] 2021-03-02 08:42
@damemi       
LowNodeUtilization strategy, is there a way to migrate only pods in the specified namespace

**Comment by damemi** [comment] 2021-03-02 17:46
@1032231418 the namespace parameters are set per-strategy, and we intentionally do not provide it for `LowNodeUtilization` due to the fact that `LowNodeUtilization` is meant to balance an entire node, so running it only against a small number of namespaces defeats the purpose of the strategy.

There is some more discussion on this in https://github.com/kubernetes-sigs/descheduler/issues/391, but the general idea is that unless your specific namespace is consuming a majority of your cluster's resources, the `LowNodeUtilization` strategy will never be able to successfully balance the node's utilization. For many cases, the other strategies are sufficient to achieve the balance most users are actually seeking within a namespace.

We can continue the discussion on adding this ability in that issue, so I'm going to close this one as a duplicate of that.
/close

**Closed by damemi** 2021-03-02 17:46 UTC
Labels: kind/support
